# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_logbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='logbot', max_length=30)),
                ('recipient', models.CharField(default='logbot', max_length=30)),
                ('message', models.CharField(max_length=30)),
                ('time_set', models.DateTimeField(verbose_name='time sent')),
            ],
        ),
    ]
